[package]
name = "graph"
version = "0.1.0"
authors = ["Florin-Vlad Sabau <sabauflorin28@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
generational-arena = "0.2.8"
rustyline = "8.0.0" 
